Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
import numpy as np

In [8]:
print(np.arange(2,51,3))

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


Accept two lists of 5 elements each from the user.

Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [10]:
list1 = [2,1,3,5,4]
list2 = [8,6,7,10,9]
print('Original List : ', list1, list2)
arr1 = np.array(list1)
arr2 = np.array(list2)
print('\n Converted Numpy Arrays : ', arr1, arr2)
concat = np.concatenate((arr1, arr2))
print('\n Concatenated array : ', concat)
sort = np.sort(concat)
print('\n Sorted array : ', sort)

Original List :  [2, 1, 3, 5, 4] [8, 6, 7, 10, 9]

 Converted Numpy Arrays :  [2 1 3 5 4] [ 8  6  7 10  9]

 Concatenated array :  [ 2  1  3  5  4  8  6  7 10  9]

 Sorted array :  [ 1  2  3  4  5  6  7  8  9 10]


Write a code snippet to find the dimensions of a ndarray and its size.

In [21]:
arr = np.random.rand(3,3,2)
print('The array : \n', arr)
print('\n Dimension of the array : ', np.ndim(arr))
print('\n Size of the array : ', np.size(arr))

The array : 
 [[[0.63554287 0.10259646]
  [0.29366506 0.04676334]
  [0.60564253 0.46018241]]

 [[0.3938452  0.63905044]
  [0.29201125 0.36190575]
  [0.35733882 0.68212654]]

 [[0.64048834 0.20398887]
  [0.77093222 0.73240034]
  [0.39872612 0.29553987]]]

 Dimension of the array :  3

 Size of the array :  18


How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet

Hint: np.newaxis, np.expand_dims

In [50]:
# Using np.newaxis
arr3 = np.random.random(5)
print('Given array : ', arr3)
print('Shape : ', arr3.shape)
arr4 = np.random.random(5).reshape(5,1)
print('\n Converting the array in 2-d : \n', arr4)
print('Shape : ', arr4.shape)

# Using np.expand_dims
arr5 = np.arange(4)
print('\n\n\nGiven array : ', arr5)
print('Shape : ', arr5.shape)
arr6 = np.expand_dims(arr5, axis=1)
print('\n Converting the array in 2-d : \n', arr6)
print('Shape : ', arr6.shape)

Given array :  [0.69613688 0.04910483 0.13137514 0.06075233 0.87842765]
Shape :  (5,)

 Converting the array in 2-d : 
 [[0.39035144]
 [0.34857783]
 [0.14798118]
 [0.61902089]
 [0.04409687]]
Shape :  (5, 1)



Given array :  [0 1 2 3]
Shape :  (4,)

 Converting the array in 2-d : 
 [[0]
 [1]
 [2]
 [3]]
Shape :  (4, 1)


Consider two square numpy arrays. Stack them vertically and horizontally.

Hint: Use vstack(), hstack()

In [61]:
ar1 = np.random.rand(2,2)
ar2 = np.random.rand(2,2)
print('ar1 : \n', ar1)
print('\n ar2 : \n', ar2)

print('\n Stack Vertically : \n', np.vstack((ar1,ar2)))
print('\n Stack Horizontally : \n', np.hstack((ar1,ar2)))

ar1 : 
 [[0.42960156 0.79439683]
 [0.38310389 0.14376158]]

 ar2 : 
 [[0.66218223 0.97769864]
 [0.19697399 0.28286774]]

 Stack Vertically : 
 [[0.42960156 0.79439683]
 [0.38310389 0.14376158]
 [0.66218223 0.97769864]
 [0.19697399 0.28286774]]

 Stack Horizontally : 
 [[0.42960156 0.79439683 0.66218223 0.97769864]
 [0.38310389 0.14376158 0.19697399 0.28286774]]


How to get unique items and counts of unique items?

In [73]:
ar = np.array([1,4,6,3,5,7,3,5,3,4,3,5,2])
print('Array : ', ar)
unique, count = np.unique(ar, return_counts=True)
print('\nUnique Items in Array : ', unique)
print('\nCount of Unique Items in Array : ', count)

Array :  [1 4 6 3 5 7 3 5 3 4 3 5 2]

Unique Items in Array :  [1 2 3 4 5 6 7]

Count of Unique Items in Array :  [1 1 4 2 3 1 1]
